version: '3.8'
services:
  db:
    image: mysql/mysql-server
    restart: always
    #SQL8 below Native password;
    command: --default-authentication-plugin=mysql_native_password 
    container_name: ZenDeskDB
    environment:
      MYSQL_DATABASE: 'ZenDeskApp'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ZenUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: '@*ePEk3SwiYu&=oVuPhi'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '@*ePEk3SwiYu&=oVuPhi'
    volumes:
        -  my-db:/var/lib/mysql
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8100:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

# Names our volume
volumes: 
  my-db: